zh-CN: # 语言: 中文
  translations: 
  - selector: 'mdui-top-app-bar-title'
    target: inner-html
    text: 博客 # 博客页面的顶部导航栏标题
  - selector: 'mdui-top-app-bar > mdui-tooltip:nth-of-type(1)'
    target: content
    text: '回到顶部' # 回到顶部按钮
  - selector: 'mdui-top-app-bar > mdui-tooltip:nth-of-type(2)'
    target: content
    text: '随机看一篇' # 搜索栏的“随机”按钮
  - selector: '.container > h1'
    target: inner-html
    text: 欢迎来到博客页面 # 博客页面的主标题
  - selector: '.container > p'
    target: inner-html
    text: 一些描述 # 博客页面的小描述
  - selector: 'mdui-collapse-item > mdui-list-item > div.h-box > span'
    target: inner-html
    text: 筛选 # 博客页面的筛选面板
  - selector: 'mdui-collapse-item > mdui-list-item > mdui-tooltip'
    target: content
    text: 切换视图（卡片/列表） # 筛选旁边的开关

  _other: 
    title: 博客 | Viderexo 示例 # 设置浏览器标签页中显示的页面标题

en: # Language: English
  translations: 
  - selector: 'mdui-top-app-bar-title'
    target: inner-html
    text: Blog # The title in the top app bar on the blog page
  - selector: 'mdui-top-app-bar > mdui-tooltip:nth-of-type(1)'
    target: content
    text: 'Back to Top' # The tooltip text for the back to top button
  - selector: 'mdui-top-app-bar > mdui-tooltip:nth-of-type(2)'
    target: content
    text: 'Random Post' # Random btn
  - selector: '.container > h1'
    target: inner-html
    text: Welcome to My Blog! # Titile of th blog page
  - selector: '.container > p'
    target: inner-html
    text: desc # desc
  - selector: 'mdui-collapse-item > mdui-list-item > div.h-box > span'
    target: inner-html
    text: Filter # Filter panel title
  - selector: 'mdui-collapse-item > mdui-list-item > mdui-tooltip'
    target: content
    text: Toggle View # Switch beside th filter

  _other: 
    title: Blog | Viderexo Demo # Sets the page title displayed in the browser tab.
