zh-CN: # 语言: 中文
  translations:
    - selector: 'body > h1'
      target: inner-html
      text: 欢迎！ # 中央大文字
    - selector: '.tops > mdui-card:nth-child(1) > span'
      target: inner-html
      text: Demo # 左上角名字
    - selector: '.bottoms > mdui-card:nth-child(1) > mdui-button:nth-child(1) > span'
      target: inner-html
      text: 介绍 # 介绍页面进入按钮
    - selector: '.bottoms > mdui-card:nth-child(1) > mdui-button:nth-child(2) > span'
      target: inner-html
      text: 链接 # 链接页面进入按钮
    - selector: '.bottoms > mdui-card:nth-child(1) > mdui-button:nth-child(3) > span'
      target: inner-html
      text: 博客 # 博客页面进入按钮
    
  _other:
    title: 首页 | Viderexo演示 # 设置浏览器标签页中显示的页面标题

en: # Language: English
  translations:
    - selector: 'body > h1'
      target: inner-html
      text: Welcome! # Central large text
    - selector: '.tops > mdui-card:nth-child(1) > span'
      target: inner-html
      text: Demo # Top-left name
    - selector: '.bottoms > mdui-card:nth-child(1) > mdui-button:nth-child(1) > span'
      target: inner-html
      text: Introduction # Introduction page entry button
    - selector: '.bottoms > mdui-card:nth-child(1) > mdui-button:nth-child(2) > span'
      target: inner-html
      text: Links # Links page entry button
    - selector: '.bottoms > mdui-card:nth-child(1) > mdui-button:nth-child(3) > span'
      target: inner-html
      text: Blog # Blog page entry button
    
  _other:
    title: Home | Viderexo Demo # Sets the page title displayed in the browser tab
